### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jesseli2002**
Created Draw.io firmware decomposition diagram

### CODE REVIEW

**Comment by jesseli2002** [comment]
Reviewers: Check if you can open the drawio file and whether it makes sense, I guess

**Comment by SilentSys** [comment]
Used the github integration on draw.io and it worked for me. This link also works for me https://app.diagrams.net/#HUBC-Rocket%2FFLARE%2Fdocs%2Fdoc%2FFirmware%20Decomposition.drawio although it points to this branch. Can someone verify that it works for them as well? If so, we can use a similar link on confluence and stuff once this gets merged.

**Comment by DSep** [comment]
@SilentSys Yup link works after authorizing 3rd party access to github. 
Love this Jesse!

**Review by DSep — APPROVED** [review]
@SilentSys Yup link works after authorizing 3rd party access to github.
Love this Jesse!
(Side note: You may have used this, but there's even a VSCode extension for working on draw.io files now [marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio))

**Pull request merged**
