### PR TITLE
States

### PR DESCRIPTION
**Pull request by jesseli2002**

### CODE REVIEW

**Review by akoen — APPROVED** [review]
Clean and no errors on my machine

**Comment by SilentSys** [comment]
CI shows PIO build errors

**Comment by SilentSys** [comment]
CI failing to build. Probably changes you made to the build system.

**Comment by jesseli2002** [comment]
Seems to potentially be issue with Googletest - forcing using an older version gets it to work, and removing a few semicolons in the googletest local copy also works fine.

**Comment by SilentSys** [comment]
CI passed on dev, what caused it to happen here?

**Comment by jesseli2002** [comment]
Probably not anymore 
Googletest has live at HEAD philosophy where they'll just update their master branch and say they have backwards compatibility - nice in theory, in practice you miss stuff
like how I have the -pedantic compiler flag turned on, which causes the build to fail

Checkout out dev and trying to build ends up with the same error.

**Comment by SilentSys** [comment]
Hmm is it possible to remove pedantic just for Googletest? Or yeah, force the version?

**Pull request merged**
