### PR TITLE
gitIgnore includes the options.h file

### PR DESCRIPTION
**Pull request by jesseli2002**

### CODE REVIEW

**Comment by jesseli2002** [comment]
It removes the options.h file when you checkout this doc (so you'll have to add it back in if we merge this, and have a backup copy somewhere)

**Comment by a-duen** [comment]
Why does the options.h file get deleted?

**Comment by jesseli2002** [comment]
> Why does the options.h file get deleted? What's the reasoning behind this?

I can't tell if it's the way adding something to the .gitignore works or i'm just stupid, but it deletes the options.h file when you checkout the branch so ¯\_(ツ)_/¯

Or it could be that I might not even be doing the .gitignore right

**Comment by a-duen** [comment]
I get what you were trying to do but we can't have the options.h file get deleted by accident

**Comment by jesseli2002** [comment]
kay so i looked into it again
and basically gitignore will only work on files that aren't tracked
which means that you have to remove the file, and readd it

**Comment by a-duen** [comment]
But if it isn't tracked, will you be able to pull it from the repository?

**Pull request closed without merging**
